name: 🐛 Bug Report
description: A report of an error in a recent version
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour you didn't see
    validations:
      required: false

  - type: textarea
    id: unexpected-behaviour
    attributes:
      label: Unexpected behaviour you saw
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the problem
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional program output to the terminal or log subsystem illustrating the issue
      description: |
        Please paste relevant program terminal or journal output here
      placeholder: This will be automatically formatted into code, so no need for backticks.
      render: sh
    validations:
      required: false
